/**
 * CineVault Primary Icon Registry
 * Powered by @devigner-ui/icons
 */

export type { IconProps, IconVariant } from '@devigner-ui/icons';

// Direct export of all commonly used icons across CineVault
export {
  // Navigation & Core
  IconHome,
  IconHome2,
  IconCompass,
  IconClapperboard,
  IconClapperboardPlay,
  IconTV,
  IconFlame,
  IconClockCircle,
  IconCalendar,
  IconBookmark,
  IconBookmarkSquare,
  IconHistory,
  IconHistory2,
  IconMagnifer,
  IconUser,
  IconUserCircle,
  IconSettings,
  IconSetting2,
  IconShield,
  IconShieldTick,
  IconShieldWarning,

  // Media & Video Player Controls
  IconPlay,
  IconPlayCircle,
  IconPause,
  IconPauseCircle,
  IconVolumeHigh,
  IconVolumeLow,
  IconVolumeCross,
  IconVolumeSlash,
  IconFullScreen,
  IconQuitFullScreen,
  IconSkipNext,
  IconSkipPrevious,
  IconForward10Seconds,
  IconBackward10Seconds,
  IconForward15Seconds,
  IconBackward15Seconds,
  IconRotateRight,
  IconRotateLeft,
  IconSubtitle,
  IconHighDefinition,
  IconHighQuality,
  Icon4K,
  IconPIP,
  IconServer,
  IconList,
  IconMusic,
  IconSoundwave,

  // Actions, Feedback & Micro-interactions
  IconHeart,
  IconCheck,
  IconCheckCircle,
  IconClose,
  IconCloseCircle,
  IconAdd,
  IconPlus,
  IconTrash,
  IconTrashBinMinimalistic,
  IconEdit,
  IconPen,
  IconCopy,
  IconShare,
  IconShare2,
  IconSquareShareLine,
  IconDownload,
  IconDownloadMinimalistic,
  IconRefresh,
  IconRestart,
  IconSend,
  IconChatRound,
  IconChatRound as IconChatCircle,
  IconWhatsapp,
  IconStar,
  IconStars,
  IconMagicStar,
  IconInfoCircle,
  IconAlertCircle,
  IconAlertTriangle,
  IconEye,
  IconEyeSlash,
  IconLock,
  IconUnlock,
  IconBolt,
  IconRadio,
  IconAward,
  IconCrown,
  IconCPU,
  IconDatabase,
  IconLayers,
  IconFilter,
  IconSliderHorizontal,
  IconSort,
  IconRoundSortVertical,
  IconTranslate,
  IconGlobal,
  IconUsersGroupRounded,
  IconMail,
  IconMonitor,
  IconLink,
  IconActivity,
  IconTag,
  IconLayoutDashboard,
  IconBarChart,
  IconBarChartMinimalistic,
  IconChartLineUp,
  IconGraphUp,
  IconPieChart,
  IconCategory,

  // Arrows & Chevrons
  IconChevronDown,
  IconChevronUp,
  IconChevronLeft,
  IconChevronRight,
  IconArrowLeft,
  IconArrowRight,
  IconArrowRightUp,
  IconRoundAltArrowRight,
  IconRoundAltArrowLeft,
  IconMenu,
  IconHamburgerMenu,
  IconMore2,
  IconLogin,
  IconLogout,
  IconBell,
  IconBellBing,
} from '@devigner-ui/icons';

// Semantic aliases for CineVault domain
export {
  IconHome as HomeIcon,
  IconClapperboardPlay as MovieIcon,
  IconTV as TvIcon,
  IconFlame as TrendingIcon,
  IconClockCircle as LatestIcon,
  IconBookmark as WatchlistIcon,
  IconHistory as HistoryIcon,
  IconMagnifer as SearchIcon,
  IconUser as ProfileIcon,
  IconSettings as SettingsIcon,
  IconPlay as PlayIcon,
  IconPause as PauseIcon,
  IconVolumeHigh as VolumeIcon,
  IconVolumeCross as MuteIcon,
  IconFullScreen as FullscreenIcon,
  IconQuitFullScreen as ExitFullscreenIcon,
  IconSkipNext as NextIcon,
  IconSkipPrevious as PrevIcon,
  IconForward10Seconds as SkipForwardIcon,
  IconBackward10Seconds as SkipBackwardIcon,
  IconHeart as FavoriteIcon,
  IconCheck as CheckIcon,
  IconPlus as AddIcon,
  IconDownloadMinimalistic as DownloadIcon,
  IconSubtitle as SubtitleIcon,
  IconHighDefinition as QualityIcon,
  IconMore2 as MoreIcon,
  IconClose as CloseIcon,
  IconArrowLeft as BackIcon,
  IconArrowRight as ForwardIcon,
  IconChevronDown as ChevronDownIcon,
  IconChevronUp as ChevronUpIcon,
  IconChevronLeft as ChevronLeftIcon,
  IconChevronRight as ChevronRightIcon,
  IconHamburgerMenu as MenuIcon,
  IconLogin as LoginIcon,
  IconLogout as LogoutIcon,
  IconBell as NotificationIcon,
  IconFilter as FilterIcon,
  IconSort as SortIcon,
  IconShare as ShareIcon,
  IconPIP as PipIcon,
  IconInfoCircle as InfoIcon,
  IconStar as StarIcon,
  IconStars as SparklesIcon,
} from '@devigner-ui/icons';
